name: gnome-klotski
adopt-info: gnome-klotski
grade: stable
confinement: strict
base: core20

slots:
  gnome-klotski:
    interface: dbus
    bus: session
    name: org.gnome.Klotski

apps:
  gnome-klotski:
    extensions: [gnome-3-38]
    command: usr/bin/gnome-klotski
    common-id: org.gnome.Klotski.desktop
    desktop: usr/share/applications/org.gnome.Klotski.desktop

parts:
  gnome-klotski:
    source: https://gitlab.gnome.org/GNOME/gnome-klotski.git
    source-type: git
    source-tag: '3.38.2'
    plugin: meson
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version $(git describe --tags --abbrev=10)
    meson-parameters: [--prefix=/snap/gnome-klotski/current/usr]
    parse-info: [usr/share/metainfo/org.gnome.Klotski.appdata.xml]

    organize:
      snap/gnome-klotski/current/usr: usr
    build-packages:
      - appstream-util
      - yelp-tools
