name: gnome-klotski
adopt-info: gnome-klotski
grade: stable
confinement: strict
base: core22

slots:
  gnome-klotski:
    interface: dbus
    bus: session
    name: org.gnome.Klotski

apps:
  gnome-klotski:
    extensions: [gnome]
    command: usr/bin/gnome-klotski
    common-id: org.gnome.Klotski.desktop
    desktop: usr/share/applications/org.gnome.Klotski.desktop

parts:
  gnome-klotski:
    source: https://gitlab.gnome.org/GNOME/gnome-klotski.git
    source-type: git
    source-tag: '3.38.2'
    source-depth: 1
# ext:updatesnap
#   version-format:
#     lower-than: '3.39'
#     no-9x-revisions: true
    plugin: meson
    override-pull: |
      craftctl default
      craftctl set version=$(git describe --tags --abbrev=10)
    meson-parameters:
      - --prefix=/usr
      - --buildtype=release
    parse-info: [usr/share/metainfo/org.gnome.Klotski.appdata.xml]
    build-packages:
      - appstream-util
      - yelp-tools
